apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todoapi.name" . }}
  labels:
    {{- include "todoapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
  selector:
    matchLabels:
      app: {{ include "todoapi.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "todoapi.name" . }}
        {{- include "todoapi.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","sleep 5"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todoapi.name" . }}-config
                  key: APP_NAME
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "todoapi.name" . }}-secrets
                  key: API_KEY
