name: build-and-push

on:
  push:
    branches: [ master ]
  pull_request:

permissions:
  contents: read
  packages: write   # needed to push to ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}/todoapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./TodoApi/TodoApi.csproj

      - name: Build
        run: dotnet build -c Release --no-restore ./TodoApi/TodoApi.csproj

      - name: Test
        run: echo "No tests yet"  # add 'dotnet test' when you have tests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (tagged by commit SHA)
        uses: docker/build-push-action@v6
        with:
          context: ./TodoApi
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image tag
        run: echo "IMAGE=${{ env.IMAGE_NAME }}:${{ github.sha }}"
